version: '3.4'

services:
  backend:
    image: backend
    build:
      context: .
      dockerfile: Source/Backend.Shared/Dockerfile
    ports:
      - 80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
